words = [
	"accessors",
	"agpl",
	"atoi",
	"busl",
	"cddl",
	"epl",
	"gocache",
	"itoa",
	"jsonschema",
	"kmgtpe",
	"mcp",
	"npmapi",
	"npmjs",
	"spdxid",
	"sspl",
	"submatch",
	"unmarshals",
	"wtfpl",
]
