words = [
    "accessors",
    "agpl",
    "atoi",
    "bodyclose",
    "busl",
    "cddl",
    "coverprofile",
    "epl",
    "errcheck",
    "errgroup",
    "errorlint",
    "gocache",
    "godotenv",
    "gofumpt",
    "golangci",
    "goroutines",
    "gosec",
    "govet",
    "itoa",
    "jsonschema",
    "kmgtpe",
    "linters",
    "mcp",
    "npmapi",
    "npmjs",
    "paralleltest",
    "spdxid",
    "sspl",
    "staticcheck",
    "submatch",
    "unmarshals",
    "wtfpl",
]
